### ISSUE TITLE
PhysChemUnitValue: meaning of UnitId and UnitSetId attributes

### ISSUE THREAD

**Issue by dlichtenberger-chemdox** [esdscom/sdscom-xml#26] opened 2015-10-21 14:47 UTC
From the XSD documentation of PhysChemUnitValue in SDSComXML 4.2.0:

> PhysChemUnitValue, used to specify a value with unit derived from a duration-independent measurement. 

The container tag has UnitId/UnitSetId attributes, just as the embedded UnitValue type - but the "outer" UnitId attribute is a free-form string16 instead of a UnitIdEnum. What is the meaning of the outer UnitId/UnitSetId attributes?

Also, when would I want to specify UnitSetId instead of UnitId (given that both are mapped to integers)?

**Comment by dirk-qualisys** [comment] 2015-10-22 14:45
I think the issue is two-fold:
* UnitIdEnum is a list of EuPhraC IDs. I like this ;) but this does not comply with the idea that SDScom should be open to any phrase catalogue.
* IMHO, having the attributes twice makes no sense.

Proposal:
1. Delete the attributes in PhysChemUnitValue, keep the ones in UnitValue.
2a. Drop UnitIdEnum completely and replace occurences with string16, or
2b. Modify UnitIdEnum into a list of SI units in latin charset.

ESKA, please comment.

**Comment by dirk-qualisys** [comment] 2015-10-22 14:46
Labeled as bug due to the EuPhraC ID issue.

**Comment by nils-eska** [comment] 2015-11-13 15:47
The SDSCOmXML offers two ways to exchange Units.

The first option is to use the UnitIdEnum. In this case, the selected value is clearly assigned to a unit and can be identified easily by the importing system.

The second way "Unit" as string32 offers the opportunity to exchange a non standardized unit value.

The Attribute "UnitSetId" is for the Norwegian Id. Please see http://pib.no/Main.aspx?Gui/UnitSet#Top

The attributes UnitId and UnitSetId in the complexType PhysChemUnitValue are obsolete an can be discarded.

**Comment by dirk-qualisys** [comment] 2015-11-15 17:09
Proposal:
- Ignore the outer attributes fo SDScom V4. These should be deleted in V5.
- We should replace "Unit" (the string) and "UnitId" (the EuPhraC Id) with an element "Unit" of type "Phrase" in V5 (not in V4 because incompatibility) in "UnitValue". So other phrase catalogues and Ids can be used.
Downside: There is no restriction on unit phrases anymore. But if we take this seriously, we should define different sets of useful units for each property.
This topic might need a telco or FTF discussion.

**Comment by dirk-qualisys** [comment] 2015-12-09 23:24
Please add outcome of meeting in Hamburg regarding human-readable unit strings.

Reassigned to V5 milestone for changing the Unit field type. Relabeled as Refactoring since bugs would/should cause a change in V4 which was decided not to do.

**Comment by Henrich-BGRCI** [comment] 2015-12-10 11:11
According to the voting at the workshop in Hamburg, the enumeration UnitIdEnum should contain not the Euphrac Ids but just the human-readable unit strings.
im not sure, if this should be done already in V4 or just in V5.

**Comment by QuenzelGISBAU** [comment] 2015-12-11 05:58
For reasons of compatibility and because this is not a bug fixing matter but just a enhancement the old UnitIdEnum should not be given up yet . But maybe an extension of the already existing UnitidEnum would be possible?

**Comment by dirk-qualisys** [comment] 2015-12-13 18:06
Interesting idea, but if users are able to fill either the EuPhraC codes or the human-readable strings, i.e. to use the strings instead of the EuPhraC IDs, that is an incompatibility again with existing implementations (the same info is transferred in a different way). By policy, this should not be implemented in V4.

**Comment by dirk-qualisys** [comment] 2016-10-13 09:30
_References to V4 and V5 use an older definition of version numbers. Compatible changes and go into 4.2.x, while others must go into V4.3 (not V5)._

**Comment by dirk-qualisys** [comment] 2016-10-13 09:47
From today's workshop in Hamburg: While the current implementation may not be the best possible solution, the group preferred not to change this. Each system must implement a mapping anyway, and the change would only improve human readability. This does not justify the implementation effort.

**Closed by dirk-qualisys** 2016-10-13 09:47 UTC
Labels: please discuss, refactoring
